# This workflow will run the Dart language specparser on the modified files in a PR

name: Spec Parser

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.dart'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 2
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        repository: dart-lang/sdk
        path: sdk
    - name: Set up JDK 11
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
      with:
        java-version: '11'
        distribution: temurin
    - name: Set up Antlr4
      run: sudo apt-get install -y antlr4
    - name: Build specparser
      run: make
      working-directory: sdk/tools/spec_parser
    - name: Check modified files
      run: sdk/tools/spec_parse.py `gh pr view ${{ github.event.number }} --json files -q '.files[].path' | grep '.dart$' | xargs ls -d 2>/dev/null`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
